# -*- coding: utf-8 -*-
"""cs23b051

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3XZt6wSdGOkNcI34kaosYfULBZUdy-O
"""

data_bits = [1, 0, 1, 0, 1, 1, 0]
nrz = []
for i in data_bits:
    x = (-1 if i == 0 else 1)
    nrz.append(x)

print(f"NRZ encoding is as follows:")
for i in nrz:
    print(i, end = " ")
print()

import numpy as np

encoding = np.array(nrz)
print(encoding)

encoding200 = np.repeat(encoding, 200)
print(encoding200)



import matplotlib.pyplot as plt

time = np.arange(len(encoding200))

plt.figure(figsize=(10, 5))
plt.plot(time, encoding200)
plt.title('NRZ Encoding with 200 bits per sample')
plt.xlabel('200 bitsper sample')
plt.ylabel('Amplitude')
plt.grid(True)
plt.ylim(-1.5, 1.5)
plt.show()


fc = 20  # Carrier frequency in Hz

# Calculate the total duration based on the length of encoding200 and sampling_rate_hz
duration_seconds = len(encoding200) / 200

t = np.linspace(0, duration_seconds, len(encoding200), endpoint=False)

carrier_signal = np.cos(2 * np.pi * fc * t)

print(f"Length of time array (t): {len(t)}")
print(f"Length of carrier signal: {len(carrier_signal)}")
print("First 10 values of carrier_signal:")
print(carrier_signal[:10])

plt.figure(figsize=(10, 4))
plt.plot(t, carrier_signal, label=f'Carrier Wave ({fc} Hz)')
plt.title('Sinusoidal Carrier Wave')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)
plt.show()



import matplotlib.pyplot as plt

time = np.arange(len(encoding200))

plt.figure(figsize=(10, 5))
plt.plot(time, encoding200)
plt.title('NRZ Encoding with 200 bits per sample')
plt.xlabel('200 bitsper sample')
plt.ylabel('Amplitude')
plt.grid(True)
plt.ylim(-1.5, 1.5)
plt.show()
