# -*- coding: utf-8 -*-
"""cs23b051

Automatically generated by Colab.

Original file is located at
https://colab.research.google.com/drive/1h3XZt6wSdGOkNcI34kaosYfULBZUdy-O
"""

import numpy as np
import matplotlib.pyplot as plt

# Data bits
data_bits = [1, 0, 1, 0, 1, 1, 0]

# NRZ encoding
nrz = [(-1 if i == 0 else 1) for i in data_bits]

print("NRZ encoding is as follows:")
for i in nrz:
    print(i, end=" ")
print()

encoding = np.array(nrz)
print(encoding)

# Repeat each bit 200 times
encoding200 = np.repeat(encoding, 200)
print(encoding200)

# Plot NRZ signal
time = np.arange(len(encoding200))
plt.figure(figsize=(10, 5))
plt.plot(time, encoding200)
plt.title('NRZ Encoding with 200 bits per sample')
plt.xlabel('200 bits per sample')
plt.ylabel('Amplitude')
plt.grid(True)
plt.ylim(-1.5, 1.5)
plt.show()

# Carrier signal
fc = 20  # Carrier frequency in Hz
duration_seconds = len(encoding200) / 200
t = np.linspace(0, duration_seconds, len(encoding200), endpoint=False)

carrier_signal = np.sin(2 * np.pi * fc * t)

print(f"Length of time array (t): {len(t)}")
print(f"Length of carrier signal: {len(carrier_signal)}")
print("First 10 values of carrier_signal:")
print(carrier_signal[:10])

plt.figure(figsize=(10, 4))
plt.plot(t, carrier_signal, label=f'Carrier Wave ({fc} Hz)')
plt.title('Sinusoidal Carrier Wave')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)
plt.show()

# AM modulation
am_signal = encoding200 * carrier_signal

print(f"Length of AM signal: {len(am_signal)}")
print("First 10 values of AM signal:")
print(am_signal[:10])

plt.figure(figsize=(12, 6))
plt.plot(t, am_signal, label='AM Modulated Signal')
plt.title('Amplitude Modulated Signal')
plt.xlabel('Time (s)')
plt.ylabel('Amplitude')
plt.legend()
plt.grid(True)
plt.show()

