# -*- coding: utf-8 -*-
"""cs23b051

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3XZt6wSdGOkNcI34kaosYfULBZUdy-O
"""

data_bits = [1, 0, 1, 0, 1, 1, 0]
nrz = []
for i in data_bits:
    x = (-1 if i == 0 else 1)
    nrz.append(x)

print(f"NRZ encoding is as follows:")
for i in nrz:
    print(i, end = " ")
print()

import numpy as np

encoding = np.array(nrz)
print(encoding)

encoding200 = np.repeat(encoding, 200)
print(encoding200)



import matplotlib.pyplot as plt

time = np.arange(len(encoding200))

plt.figure(figsize=(10, 5))
plt.plot(time, encoding200)
plt.title('NRZ Encoding with 200 bits per sample')
plt.xlabel('200 bitsper sample')
plt.ylabel('Amplitude')
plt.grid(True)
plt.ylim(-1.5, 1.5)
plt.show()

